export const CARD_ADMIN_REQUEST = "CARD_ADMIN_REQUEST";
export const CARD_ADMIN_SUCCESS = "CARD_ADMIN_SUCCESS";
export const CARD_ADMIN_FAIL = "CARD_ADMIN_FAIL";
export const CARD_ADMIN_RESET = "CARD_ADMIN_RESET";


export const GET_MONTH_REQUEST = "GET_MONTH_REQUEST";
export const GET_MONTH_SUCCESS = "GET_MONTH_SUCCESS";
export const GET_MONTH_FAIL = "GET_MONTH_FAIL";
export const GET_MONTH_RESET = "GET_MONTH_RESET";


export const GET_CONTRACT_REQUEST = "GET_CONTRACT_REQUEST";
export const GET_CONTRACT_SUCCESS = "GET_CONTRACT_SUCCESS";
export const GET_CONTRACT_FAIL = "GET_CONTRACT_FAIL";
export const GET_CONTRACT_RESET = "GET_CONTRACT_RESET";