export const ADD_CARD_REQUEST = "ADD_CARD_REQUEST";
export const ADD_CARD_SUCCESS = "ADD_CARD_SUCCESS";
export const ADD_CARD_FAIL = "ADD_CARD_FAIL";
export const ADD_CARD_RESET = "ADD_CARD_RESET";


export const GET_CARD_DETAIL_REQUEST = "GET_CARD_DETAIL_REQUEST";
export const GET_CARD_DETAIL_SUCCESS = "GET_CARD_DETAIL_SUCCESS";
export const GET_CARD_DETAIL_FAIL = "GET_CARD_DETAIL_FAIL";
export const GET_CARD_DETAIL_RESET = "GET_CARD_DETAIL_RESET";

export const DELETE_CARD_DETAIL_REQUEST = "DELETE_CARD_DETAIL_REQUEST";
export const DELETE_CARD_DETAIL_SUCCESS = "DELETE_CARD_DETAIL_SUCCESS";
export const DELETE_CARD_DETAIL_FAIL = "DELETE_CARD_DETAIL_FAIL";
export const DELETE_CARD_DETAIL_RESET = "DELETE_CARD_DETAIL_RESET";