export const GET_ALL_REQUEST_REQUEST = "GET_ALL_REQUEST_REQUEST";
export const GET_ALL_REQUEST_SUCCESS = "GET_ALL_REQUEST_SUCCESS";
export const GET_ALL_REQUEST_FAIL = "GET_ALL_REQUEST_FAIL";
export const GET_ALL_REQUEST_RESET = "GET_ALL_REQUEST_RESET";


export const CONFIRM_REQUEST_REQUEST = "CONFIRM_REQUEST_REQUEST";
export const CONFIRM_REQUEST_SUCCESS = "CONFIRM_REQUEST_SUCCESS";
export const CONFIRM_REQUEST_FAIL = "CONFIRM_REQUEST_FAIL";
export const CONFIRM_REQUEST_RESET = "CONFIRM_REQUEST_RESET";