export const GET_ALL_REQUEST_REQUEST = "GET_ALL_REQUEST_REQUEST";
export const GET_ALL_REQUEST_SUCCESS = "GET_ALL_REQUEST_SUCCESS";
export const GET_ALL_REQUEST_FAIL = "GET_ALL_REQUEST_FAIL";
export const GET_ALL_REQUEST_RESET = "GET_ALL_REQUEST_RESET";
