export const LIST_STAFF_REQUEST = "LIST_STAFF_REQUEST";
export const LIST_STAFF_SUCCESS = "LIST_STAFF_SUCCESS";
export const LIST_STAFF_FAIL = "LIST_STAFF_FAIL";
export const LIST_STAFF_RESET = "LIST_STAFF_RESET";

export const USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const USER_INFO_FAIL = "USER_INFO_FAIL";
export const USER_INFO_RESET = "USER_INFO_RESET";

export const STAFF_STATUS_REQUEST = "STAFF_STATUS_REQUEST";
export const STAFF_STATUS_SUCCESS = "STAFF_STATUS_SUCCESS";
export const STAFF_STATUS_FAIL = "STAFF_STATUS_FAIL";
export const STAFF_STATUS_RESET = "STAFF_STATUS_RESET";